### ISSUE TITLE
adkats script in data base

### ISSUE THREAD

**Issue by Kracklin** [AdKats/AdKats#1001]
> [12:23:30 61] [AdKats] ENABLED! Beginning startup sequence...
[12:23:31 47] [AdKats] SUCCESS: Fetched 111 BF4 weapon stat definitions.
[12:23:31 52] [AdKats] SUCCESS: Fetched reputation definitions.
[12:23:31 58] [AdKats] SUCCESS: Fetched weapon information.
[12:23:31 63] [AdKats] SUCCESS: Fetched special player group definitions.
[12:23:31 64] [AdKats] SUCCESS: Server IP is REDACTED
[12:23:31 85] [AdKats] SUCCESS: Database connection open.
[12:23:34 26] [AdKats] INFO: AdKats statistics table not found. Attempting to add.
[12:23:34 48] [AdKats] CREATE TABLE `adkats_statistics` (
                      `stat_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
                      `server_id` SMALLINT(5) UNSIGNED NOT NULL,
                      `round_id` INT(10) UNSIGNED NOT NULL,
                      `stat_type` varchar(50) NOT NULL,
                      `target_name` varchar(50) NOT NULL,
                      `target_id` INT(10) UNSIGNED DEFAULT NULL,
                      `stat_value` FLOAT NOT NULL,
                      `stat_comment` TEXT,
                      `stat_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
                      PRIMARY KEY (`stat_id`),
                      KEY `server_id` (`server_id`),
                      KEY `stat_type` (`stat_type`),
                      KEY `target_id` (`target_id`),
                      KEY `stat_time` (`stat_time`),
                      CONSTRAINT `adkats_statistics_target_id_fk` FOREIGN KEY (`target_id`) REFERENCES `tbl_playerdata` (`PlayerID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
                      CONSTRAINT `adkats_statistics_server_id_fk` FOREIGN KEY (`server_id`) REFERENCES `tbl_server` (`ServerID`) ON DELETE NO ACTION ON UPDATE NO ACTION
                    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='AdKats - Statistics'
[12:23:34 48] [AdKats] ERROR-75054: [Non-Query failed. [Adding AdKats statistics table]: MySql.Data.MySqlClient.MySqlException: Invalid default value for 'stat_time'
   at PRoConEvents.AdKats.SafeExecuteNonQuery(MySqlCommand command)
   at PRoConEvents.AdKats.SendNonQuery(String desc, String nonQuery, Boolean verbose)]
[12:23:35 48] [AdKats] INFO: AdKats role groups table not found. Attempting to add.
[12:23:35 72] [AdKats] CREATE TABLE `adkats_rolegroups` (
                      `role_id` int(11) unsigned NOT NULL,
                      `group_key` VARCHAR(100) NOT NULL,
                      PRIMARY KEY (`role_id`,`group_key`),
                      KEY `adkats_rolegroups_fk_role` (`role_id`),
                      KEY `adkats_rolegroups_fk_command` (`group_key`),
                      CONSTRAINT `adkats_rolegroups_fk_role` FOREIGN KEY (`role_id`) REFERENCES `adkats_roles` (`role_id`) ON DELETE CASCADE ON UPDATE CASCADE
                    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='AdKats - Connection of groups to roles'
[12:23:35 72] [AdKats] ERROR-75054: [Non-Query failed. [Adding AdKats role groups table]: MySql.Data.MySqlClient.MySqlException: Cannot add foreign key constraint
   at PRoConEvents.AdKats.SafeExecuteNonQuery(MySqlCommand command)
   at PRoConEvents.AdKats.SendNonQuery(String desc, String nonQuery, Boolean verbose)]
[12:23:37 12] [AdKats] ALTER TABLE adkats_settings MODIFY setting_value varchar(10000)
[12:23:37 73] [AdKats] ERROR-75054: [AdKats tables not present or valid in the database. Have you run the AdKats database setup script yet? If so, are your tables InnoDB?]
[12:23:37 73] [AdKats] INFO: Shutting down AdKats.
[12:23:38 09] [AdKats] SUCCESS: Database timing confirmed.
[12:23:42 52] [AdKats] AdKats 7.5.0.54 Disabled! =(

**Comment by ColColonCleaner** [comment]
Hey mamba. The screenshot you sent me in the PM shows you were using a table suffix. That needs to be removed. Please remove all the tables from your database and start over. Removing all tables on your own is a little involved, so please just ask your database host to do it.
Then set up stat logger without a table suffix, run it for a while, then run the adkats setup script, then run adkats.
Cheers.

**Comment by Kracklin** [comment]
Hey man! I figured that and it’s now working!! Thanks for helping me

**Comment by ColColonCleaner** [comment]
Glad it's working. Closing issue.
