### ISSUE TITLE
 Error while confirming table 'tbl_playerdata' - On first start.

### ISSUE THREAD

**Issue by tek0011** [AdKats/AdKats#1041]
PRoCon Chat, GUID, Stats and Map Logger - 1.0.0.3 is installed and working.
DB script was ran and executed successfully. 

Getting the following error on first start.  

```
[16:09:24 70] [AdKats] ENABLED! Beginning startup sequence...
[16:09:25 61] In-Game Admin Disabled =(
[16:09:25 89] [AdKats] SUCCESS: Fetched 111 BF4 weapon stat definitions.
[16:09:25 96] [AdKats] SUCCESS: Fetched reputation definitions.
[16:09:26 11] [AdKats] SUCCESS: Fetched weapon information.
[16:09:26 19] [AdKats] SUCCESS: Fetched special player group definitions.
[16:09:26 36] [AdKats] SUCCESS: Global timing confirmed.
[16:09:26 36] [AdKats] SUCCESS: Server IP is <REDACTED>
[16:09:26 56] [AdKats] SUCCESS: Database connection open.
[16:09:26 62] [AdKats] EXCEPTION-7611-P0.23-D-ConfirmTable-DatabaseComm105: [Error while confirming table 'tbl_playerdata'][System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at PRoConEvents.AdKats.SafeExecuteReader(MySqlCommand command)
   at PRoConEvents.AdKats.ConfirmTable(String tableName)]
[16:09:27 63] [AdKats] EXCEPTION-7611-P0.23-GetCommandByKey-DatabaseComm105: [Unable to get command for key 'adkats_exception']
[16:09:36 94] [AdKats] INFO: Shutting down AdKats.
[16:09:36 96] [AdKats] ERROR-7611: [Tables from XPKiller's Stat Logger not present in the database. Enable that plugin then re-run AdKats!]
[16:09:37 19] [AdKats] SUCCESS: Database timing confirmed.
[16:09:42 05] [AdKats] AdKats 7.6.1.1 Disabled! =(
```

Any idea on how to resolve this?

**Comment by Hedius** [comment]
Yes. RTFM
+ RTF error message

ERROR-7611: [Tables from XPKiller's Stat Logger not present in the database. Enable that plugin then re-run AdKats!]

You did not follow the instructions!

**Comment by tek0011** [comment]
> Yes. RTFM
> 
> * RTF error message
> 
> ERROR-7611: [Tables from XPKiller's Stat Logger not present in the database. Enable that plugin then re-run AdKats!]
> 
> You did not follow the instructions!

As stated, we have that plugin enabled, and it is working correctly.

**Comment by Hedius** [comment]
I do not believe you.
Did you follow the instructions?
The error msg clearly shows that the chatlogger tables are missing in the database you use for AdKats.

**Comment by tek0011** [comment]
Here is the output from trace:
```
[10:08:04 57] [Statslogger]Trace: Insert for Player OddJob001
[10:08:04 57] [Statslogger]Trace: ClanTag 
[10:08:04 57] [Statslogger]Trace: SoldierName OddJob001
[10:08:04 57] [Statslogger]Trace: PBGUID e2ca6cc384a5f3e766890ddfd6f26322
[10:08:04 57] [Statslogger]Trace: EAGUID EA_8C4CD91F8137BA4365CF87493D333FB6
[10:08:04 57] [Statslogger]Trace: IP_Address <REDACTED>
[10:08:04 57] [Statslogger]Trace: CountryCode us
[10:08:04 57] [Statslogger]Trace: GlobalRank 140
[10:08:04 59] [Statslogger]Trace: Insert for Player Sterben026
[10:08:04 59] [Statslogger]Trace: ClanTag 
[10:08:04 59] [Statslogger]Trace: SoldierName Sterben026
[10:08:04 59] [Statslogger]Trace: PBGUID ccc05ce25b95353978ffb0d1f038023a
[10:08:04 59] [Statslogger]Trace: EAGUID EA_39F485B4BE4D69FADAAD462BC4D1EF02
[10:08:04 59] [Statslogger]Trace: IP_Address <REDACTED>
[10:08:04 59] [Statslogger]Trace: CountryCode us
[10:08:04 59] [Statslogger]Trace: GlobalRank 109
[10:08:04 62] [Statslogger]Trace: tbl_server_player Write querys
[10:08:04 70] [Statslogger]Trace: PlayerID: 1
[10:08:04 70] [Statslogger]Trace: StatsID: 0
[10:08:04 70] [Statslogger]Trace: Insert PlayerID 1into tbl_server_player
[10:08:04 72] [Statslogger]Trace: PlayerID: 2
[10:08:04 72] [Statslogger]Trace: StatsID: 0
[10:08:04 72] [Statslogger]Trace: Insert PlayerID 2into tbl_server_player
[10:08:04 75] [Statslogger]Trace: Combatstats Write querys
[10:08:04 83] [Statslogger]Trace: PlayerID: 1
[10:08:04 83] [Statslogger]Trace: StatsID: 1
[10:08:04 85] [Statslogger]Trace: Weaponstats Write querys
[10:08:04 85] [Statslogger]Trace: PlayerID: 2
[10:08:04 85] [Statslogger]Trace: StatsID: 2
[10:08:04 86] [Statslogger]Trace: Weaponstats Write querys
[10:08:04 91] [Statslogger]Trace: Dogtagstats Write querys
[10:08:04 96] [Statslogger]Trace: 0 Sessions to write to Sessiontable
[10:08:04 98] [Statslogger]Trace: Serverstats Write query
[10:08:05 06] [Statslogger]Info: Status ID-Cache: 2 ID's in cache
[10:08:05 06] [Statslogger]Info: Connection MySqlConn closed
```

And the view from the DB:
https://i.imgur.com/vsIzucJ.png

**Comment by Hedius** [comment]
There are not any AdKats tables. Did you read the manual? And follow the instructions? And run the SQL script on the database????

**Comment by tek0011** [comment]
Yes, as stated in the original message:
> DB script was ran and executed successfully.

The above image is from `Chat, GUID, Stats and Mapstats Logger [1.0.0.3]` - before the sql script was ran.  I will go query the db again and show you what it looks like after the script was executed.

**Comment by tek0011** [comment]
Database screenshot
https://i.imgur.com/OYYI4oA.png

**Comment by tek0011** [comment]
Im going to guess this is an issue with the `Chat, GUID, Stats and Mapstats Logger [1.0.0.3]` plugin:

```
SELECT * FROM `tbl_playerdata` WHERE 1
MySQL returned an empty result set (i.e. zero rows). (Query took 0.0206 seconds.)
```

**Comment by Hedius** [comment]
Is the database new? I would suggest that you wipe it and start with a fresh one.

Let the stats logger run for a few rounds. (Check your stats logger settings make sure that everything is enabled) 

Use the lates version from myrcon.net (if 1.0.0.3 is not the newest version)


Check for stats logger exception. If there some.

If stats logger is filling every table with data: run the setup script

And then adkats

**Comment by tek0011** [comment]
The first time, we let stats logger run for about 4-5 hours.  Things were working fine.  We then ran the sql script and stats logger stopped working.  
We then wiped the DB, and tried it all again with the same issue.  Maybe its an issue with 1.0.03..

Let me look for a newer version.  I was just following the [install page,](https://github.com/AdKats/AdKats#install) that sends you here:  https://myrcon.net/topic/162-chat-guid-stats-and-mapstats-logger-1003/

**Comment by tek0011** [comment]
Im not seeing a newer version, 1.0.0.3 is showing as latest.

**Comment by tek0011** [comment]
We've now let 5 rounds play through, and all seems to be working with `Chat, GUID, Stats and Mapstats Logger [1.0.0.3]` (still havent found a different version).  

https://i.imgur.com/4VStrsW.png

I'll try applying the SQL script now.

**Comment by tek0011** [comment]
Same error: 
```
[14:31:15 26] [AdKats] EXCEPTION-7611-P2.87-D-ConfirmTable-DatabaseComm32: [Error while confirming table 'tbl_playerdata'][System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at PRoConEvents.AdKats.SafeExecuteReader(MySqlCommand command)
   at PRoConEvents.AdKats.ConfirmTable(String tableName)]
```

**Comment by tek0011** [comment]
Anything else we can try?  Im fairly certain the issue is the sql script.  I havent pinned down where yet, but `Chat, GUID, Stats and Mapstats Logger [1.0.0.3]` works, right up to the point that we run the sql script per adkats install.  Then we hit issues.

**Comment by tek0011** [comment]
Never did resolve this. Moved services to ezrcon and it's all working.
