### ISSUE TITLE
0.3.4.9 beta errors

### ISSUE THREAD

**Issue by Hutchew** [AdKats/AdKats#237]
Running beta version 0.3.4.9 and stat logger update as well.

Our #1 and #4 servers show this error:

[09:18:21 89] [AdKats] EXCEPTION: [OnServerInfo][Error while processing server info.]: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.ThrowHelper.ThrowArgumentOutOfRangeException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at PRoConEvents.AdKats.OnServerInfo(CServerInfo serverInfo)
[09:18:32 03] [AdKats] EXCEPTION: [OnServerInfo][Error while processing server info.]: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.ThrowHelper.ThrowArgumentOutOfRangeException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at PRoConEvents.AdKats.OnServerInfo(CServerInfo serverInfo)
[09:18:32 22] [AdKats] EXCEPTION: [OnServerInfo][Error while processing server info.]: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.ThrowHelper.ThrowArgumentOutOfRangeException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at PRoConEvents.AdKats.OnServerInfo(CServerInfo serverInfo)
[09:18:46 23] [AdKats] EXCEPTION: [OnServerInfo][Error while processing server info.]: System.NullReferenceException: Object reference not set to an instance of an object.
   at PRoConEvents.AdKats.OnServerInfo(CServerInfo serverInfo)

Our #2 server doesn't show the above error, but a previously banned player will generate this one:
[04:29:51 18] [AdKats] OnBanList fired
[04:29:51 18] [AdKats] Bans found
[04:29:51 19] [AdKats] ERROR: Attempted to fetch player with no information.
[04:29:51 19] [AdKats] EXCEPTION: [databaseCommThreadLoop][Error occured in database comm thread.]: System.NullReferenceException: Object reference not set to an instance of an object.
   at PRoConEvents.AdKats.databaseCommThreadLoop()

Any ideas?

**Comment by ColColonCleaner** [comment]
https://github.com/isaacs/github/issues/253
