### ISSUE TITLE
AdKats Eception - actionHandlingThreadLoop

### ISSUE THREAD

**Issue by Phenom300** [AdKats/AdKats#250]
Here's another

[19:11:22 10] [MULTIbalancer]:0 Thread(scrambler): ScramblerLoop thread stopped
[19:11:22 10] [AdKats] EXCEPTION: [actionHandlingThreadLoop][Action handling thread aborted. Attempting to restart.]: System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.WaitHandle.WaitOneNative(SafeWaitHandle waitHandle, UInt32 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.WaitOne(Int64 timeout, Boolean exitContext)
   at System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout, Boolean exitContext)
   at System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout)
   at PRoConEvents.AdKats.actionHandlingThreadLoop()

**Comment by ColColonCleaner** [comment]
https://github.com/isaacs/github/issues/253
