### ISSUE TITLE
Exception 4442 OnServerInfo

### ISSUE THREAD

**Issue by ColColonCleaner** [AdKats/AdKats#512]
[OnServerInfo][Error while processing server info.]: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at PRoConEvents.AdKats.OnServerInfo(CServerInfo serverInfo) in c:\Users\gradinjand\Downloads\procon1-531\builds\Debug\Plugins\BF4\Temp\h83j9za-.0.cs:line 4442

**Comment by ColColonCleaner** [comment]
Fixed in #655
