### ISSUE TITLE
Bug at the end of the round

### ISSUE THREAD

**Issue by ChaT0n** [AdKats/AdKats#798]
On adkats v 6.8.0.0 and BF3 server:

[AdKats] EXCEPTION-6800-D-HandleActiveBanEnforcer-DatabaseComm26: [Error while handling active ban enforcer.][System.ArgumentException: Offset und Länge für das Array liegen außerhalb des gültigen Bereichs, oder die Anzahl ist größer als die Anzahl der Elemente vom Index bis zum Ende der Quellauflistung.

For the translation: Offset and length of the array are out of range, or the number is greater than the number of elements from index to the end of the source collection.

**Comment by ColColonCleaner** [comment]
I"ll look into it. For the future please enable plugin debugging on your layer.

**Comment by schodoodles** [comment]
Think I may also be experiencing this;
[23:09:08 63] [AdKats] EXCEPTION-6800-D-FetchUserList-AccessFetching41: [Error while fetching user list.][System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlDataReader.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlDataReader.GetValue(Int32 i)
   at MySql.Data.MySqlClient.MySqlDataReader.IsDBNull(Int32 i)
   at PRoConEvents.AdKats.FetchUserList()]

Just installed new version on ProCon layer and reset the DB so all was fresh.

**Comment by ColColonCleaner** [comment]
Please enable plugin debugging on your layer.

**Comment by schodoodles** [comment]
Tried 3 but nothing really came up[ that was helpful; tried today at level 5 logging and the below was given. I tried assigning user in-game players to users of the same name in the DB to give them admin but this failed with an invalid game id error for all of them. 

Updating Setting Page [Main]: 6.9043949 seconds since last update.
[21:33:52 05] [AdKats] Updating Setting Page [Main]: 0.0070004 seconds since last update.
[21:33:52 37] [AdKats] Exiting a user change thread.
[21:33:52 37] [AdKats] Uploading user: KillaPlayer1
[21:33:52 80] [AdKats] User uploaded to database SUCCESSFULY.
[21:33:53 10] [AdKats] Soldier link 5->29 uploaded to database SUCCESSFULY.
[21:33:53 96] [AdKats] Command fetch took 866.0495ms.
[21:33:54 68] [AdKats] Role fetch took 719.0411ms.
[21:33:55 06] [AdKats] Team Info: RU: 3/32 CN: 2/32
[21:33:55 11] [AdKats] User fetch (Users) took 427.0245ms.
[21:33:55 26] [AdKats] EXCEPTION-6800-D-FetchUserList-AccessFetching26: [Error while fetching user list.][System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlDataReader.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlDataReader.GetValue(Int32 i)
   at MySql.Data.MySqlClient.MySqlDataReader.IsDBNull(Int32 i)
   at PRoConEvents.AdKats.FetchUserList()]
[21:33:55 26] [AdKats] Preparing to check adkats_exception record for pre-upload processing.
[21:33:55 26] [AdKats] Unprocessed Record: 1 Current: 0
[21:33:55 26] [AdKats] Team Info: RU: 3/32 CN: 2/32
[21:33:55 26] [AdKats] No inbound player listing actions. Waiting for Input.
[21:33:55 26] [AdKats] Unprocessed Record: 0 Current: 1
[21:33:55 26] [AdKats] Entering handle record upload
[21:33:55 26] [AdKats] Record needs full upload, checking.
[21:33:55 26] [AdKats] UPLOADING record for Logged Exception
[21:33:55 30] [AdKats] Reserved slots listed.
[21:33:55 33] [AdKats] Spectators listed.
[21:33:55 33] [AdKats] Spectators listed.
[21:33:55 36] [AdKats] User fetch (Orchestration) took 100.0058ms.
[21:33:55 36] [AdKats] User List Fetched from Database. [5 users, 0 Special Players]
[21:33:55 36] [AdKats] Updating Setting Page [AccessFetching]: 3.3081892 seconds since last update.
[21:33:55 37] [AdKats] Updating Setting Page [AccessFetching]: 0.0110006 seconds since last update.
[21:33:55 42] [AdKats] User fetch took 733.042ms.
[21:33:55 42] [AdKats] Access fetch waiting for Input.
[21:33:55 42] [AdKats] Warning. AccessFetching thread processing completed in 2318ms
[21:33:55 69] [AdKats] adkats_exception upload for AdKats by AdKats SUCCESSFUL!
[21:33:55 70] [AdKats] adkats_exception last used 9s ago.
[21:33:56 12] [AdKats] Unprocessed Record: 1 Current: 0
[21:33:56 12] [AdKats] Unprocessed Record: 0 Current: 1
[21:33:56 12] [AdKats] Entering handle record upload
[21:33:56 12] [AdKats] UPDATING record for Logged Exception
[21:33:56 56] [AdKats] Updating endpoint reputation for Logged Exception record.
[21:33:56 56] [AdKats] adkats_exception update for AdKats by AdKats SUCCESSFUL!
[21:33:56 56] [AdKats] In-Game/Automated adkats_exception record took 1302ms to complete actions.
[21:34:00 26] [AdKats] Team Info: RU: 3/32 CN: 2/32
[21:34:00 88] [AdKats] Starting a user change thread.
[21:34:00 98] [AdKats] Updating Setting Page [Main]: 5.6143211 seconds since last update.
[21:34:00 99] [AdKats] Updating Setting Page [Main]: 0.0070004 seconds since last update.
[21:34:01 31] [AdKats] Uploading user: schodoodles
[21:34:01 31] [AdKats] Exiting a user change thread.
[21:34:01 36] [AdKats] Listing Players
[21:34:01 36] [AdKats] Team Info: RU: 3/32 CN: 2/32
[21:34:01 36] [AdKats] No inbound player listing actions. Waiting for Input.
[21:34:01 74] [AdKats] User uploaded to database SUCCESSFULY.
[21:34:02 04] [AdKats] Soldier link 1->1 uploaded to database SUCCESSFULY.
[21:34:02 90] [AdKats] Command fetch took 861.0492ms.
[21:34:03 62] [AdKats] Role fetch took 717.041ms.
[21:34:04 04] [AdKats] User fetch (Users) took 428.0245ms.
[21:34:04 19] [AdKats] EXCEPTION-6800-D-FetchUserList-AccessFetching26: [Error while fetching user list.][System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlDataReader.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlDataReader.GetValue(Int32 i)
   at MySql.Data.MySqlClient.MySqlDataReader.IsDBNull(Int32 i)
   at PRoConEvents.AdKats.FetchUserList()]
[21:34:04 19] [AdKats] Preparing to check adkats_exception record for pre-upload processing.
[21:34:04 19] [AdKats] Unprocessed Record: 1 Current: 0
[21:34:04 19] [AdKats] Role for authorized player Schodoodles has been CHANGED to Full Admin.
[21:34:04 19] [AdKats] Unprocessed Record: 0 Current: 1
[21:34:04 19] [AdKats] Entering handle record upload
[21:34:04 19] [AdKats] Record needs full upload, checking.
[21:34:04 19] [AdKats] UPLOADING record for Logged Exception
[21:34:04 19] [AdKats] Reserved slots listed.
[21:34:04 21] [AdKats] Team Info: RU: 3/32 CN: 2/32
[21:34:04 21] [AdKats] No inbound player listing actions. Waiting for Input.
[21:34:04 29] [AdKats] User fetch (Orchestration) took 100.0057ms.
[21:34:04 29] [AdKats] User List Fetched from Database. [5 users, 0 Special Players]
[21:34:04 29] [AdKats] Updating Setting Page [AccessFetching]: 3.3021889 seconds since last update.
[21:34:04 29] [AdKats] Spectators listed.
[21:34:04 30] [AdKats] Spectators listed.
[21:34:04 30] [AdKats] Updating Setting Page [AccessFetching]: 0.0070004 seconds since last update.
[21:34:04 34] [AdKats] User fetch took 722.0413ms.
[21:34:04 34] [AdKats] Access fetch waiting for Input.
[21:34:04 34] [AdKats] Warning. AccessFetching thread processing completed in 2302ms
[21:34:04 62] [AdKats] adkats_exception upload for AdKats by AdKats SUCCESSFUL!
[21:34:04 63] [AdKats] adkats_exception last used 8s ago.
[21:34:04 63] [AdKats] Unprocessed Record: 1 Current: 0
[21:34:04 63] [AdKats] Unprocessed Record: 0 Current: 1
[21:34:04 63] [AdKats] Entering handle record upload
[21:34:04 63] [AdKats] UPDATING record for Logged Exception
[21:34:05 07] [AdKats] Updating endpoint reputation for Logged Exception record.
[21:34:05 07] [AdKats] adkats_exception update for AdKats by AdKats SUCCESSFUL!
[21:34:05 07] [AdKats] In-Game/Automated adkats_exception record took 876ms to complete actions.
[21:34:07 35] [AdKats] Starting a user change thread.
[21:34:07 45] [AdKats] Updating Setting Page [Main]: 3.1531804 seconds since last update.
[21:34:07 46] [AdKats] Updating Setting Page [Main]: 0.0070004 seconds since last update.
[21:34:07 78] [AdKats] Exiting a user change thread.
[21:34:08 21] [AdKats] Uploading user: JustNoOne
[21:34:08 65] [AdKats] User uploaded to database SUCCESSFULY.
[21:34:08 79] [AdKats] Warning. DatabaseComm thread processing completed in 1011ms
[21:34:09 22] [AdKats] Team Info: RU: 3/32 CN: 2/32
[21:34:09 66] [AdKats] Command fetch took 867.0496ms.
[21:34:10 37] [AdKats] Role fetch took 713.0408ms.
[21:34:10 80] [AdKats] User fetch (Users) took 428.0245ms.
[21:34:10 95] [AdKats] EXCEPTION-6800-D-FetchUserList-AccessFetching26: [Error while fetching user list.][System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlDataReader.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlDataReader.GetValue(Int32 i)
   at MySql.Data.MySqlClient.MySqlDataReader.IsDBNull(Int32 i)
   at PRoConEvents.AdKats.FetchUserList()]
[21:34:10 95] [AdKats] Preparing to check adkats_exception record for pre-upload processing.
[21:34:10 95] [AdKats] Unprocessed Record: 1 Current: 0
[21:34:10 95] [AdKats] Team Info: RU: 3/32 CN: 2/32
[21:34:10 95] [AdKats] No inbound player listing actions. Waiting for Input.
[21:34:10 95] [AdKats] Unprocessed Record: 0 Current: 1
[21:34:10 95] [AdKats] Entering handle record upload
[21:34:10 95] [AdKats] Record needs full upload, checking.
[21:34:10 95] [AdKats] UPLOADING record for Logged Exception
[21:34:10 96] [AdKats] Reserved slots listed.
[21:34:11 03] [AdKats] Spectators listed.
[21:34:11 03] [AdKats] Spectators listed.
[21:34:11 05] [AdKats] User fetch (Orchestration) took 100.0057ms.
[21:34:11 05] [AdKats] User List Fetched from Database. [5 users, 0 Special Players]
[21:34:11 05] [AdKats] Updating Setting Page [AccessFetching]: 3.5902053 seconds since last update.
[21:34:11 06] [AdKats] Updating Setting Page [AccessFetching]: 0.0060003 seconds since last update.
[21:34:11 10] [AdKats] User fetch took 726.0415ms.
[21:34:11 10] [AdKats] Access fetch waiting for Input.
[21:34:11 10] [AdKats] Warning. AccessFetching thread processing completed in 2307ms
[21:34:11 38] [AdKats] adkats_exception upload for AdKats by AdKats SUCCESSFUL!
[21:34:11 39] [AdKats] adkats_exception last used 6s ago.
[21:34:11 39] [AdKats] Unprocessed Record: 1 Current: 0
[21:34:11 39] [AdKats] Unprocessed Record: 0 Current: 1
[21:34:11 39] [AdKats] Entering handle record upload
[21:34:11 39] [AdKats] UPDATING record for Logged Exception
[21:34:11 82] [AdKats] Updating endpoint reputation for Logged Exception record.
[21:34:11 82] [AdKats] adkats_exception update for AdKats by AdKats SUCCESSFUL!
[21:34:11 82] [AdKats] In-Game/Automated adkats_exception record took 877ms to complete actions.
[21:34:15 95] [AdKats] Team Info: RU: 3/32 CN: 2/32
[21:34:19 80] [AdKats] Listing Players
[21:34:19 80] [AdKats] Team Info: RU: 3/32 CN: 2/32
[21:34:19 80] [AdKats] No inbound player listing actions. Waiting for Input.

**Comment by ColColonCleaner** [comment]
Please open a new issue if this is still occurring, and please enable plugin debugging on the issue layer before submitting the error message. Thank you.
