### ISSUE TITLE
Error on test 6.8.0.26

### ISSUE THREAD

**Issue by ChaT0n** [AdKats/AdKats#811]
[14:51:27 57] [AdKats] EXCEPTION-68026-D-FetchPlayerStatInformation-HackerChecker50: [Error while parsing player stats data.][System.ArgumentOutOfRangeException: Number must be either non-negative and less than or equal to Int32.MaxValue or -1.
Parameter name: timeout
   at System.Threading.WaitHandle.WaitOne(TimeSpan timeout, Boolean exitContext)
   at System.Threading.WaitHandle.WaitOne(TimeSpan timeout)
   at PRoConEvents.AdKats.DoBattlelogWait()
   at PRoConEvents.AdKats.FetchPlayerStatInformation(AdKatsPlayer aPlayer)]
[14:51:27 85] [AdKats] EXCEPTION-68026-D-FetchPlayerBattlelogInformation-BattlelogComm51: [Error while parsing player battlelog data.][System.ArgumentOutOfRangeException: Number must be either non-negative and less than or equal to Int32.MaxValue or -1.
Parameter name: timeout
   at System.Threading.WaitHandle.WaitOne(TimeSpan timeout, Boolean exitContext)
   at System.Threading.WaitHandle.WaitOne(TimeSpan timeout)
   at PRoConEvents.AdKats.DoBattlelogWait()
   at PRoConEvents.AdKats.FetchPlayerBattlelogInformation(AdKatsPlayer aPlayer)]
[14:52:21 14] [AdKats] ERROR-68026: [Could not find Jessie-RockeTeaM in player dictionary on spawn.]

**Comment by ColColonCleaner** [comment]
Hmm, that's odd. Alright i'll look into it.

Please enable plugin debugging on your layer.

**Comment by ChaT0n** [comment]
The errors haven't showed up again for this one, but i'll keep on watching

**Comment by ColColonCleaner** [comment]
This was fixed last night, among a couple other things.
