### ISSUE TITLE
email error

### ISSUE THREAD

**Issue by ChaT0n** [AdKats/AdKats#815]
First error on  the 29th of sept : [AdKats] EXCEPTION-68039-42524-EmailProcessingThreadLoop-EmailProcessing13: [Error occured in mail processing thread. skipping loop.][System.Net.Mail.SmtpException: The operation has timed out.
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at PRoConEvents.AdKats.EmailHandler.EmailProcessingThreadLoop() in c:\Users\B\Desktop\Procon\Golmud\Plugins\BF4\Temp\mruahtv3.0.cs:line 42524]

Second error on the 30th of october : [AdKats] EXCEPTION-68039-42272-<SendReport>b__d8f-EmailSending10: [Error in email sending thread.][System.NullReferenceException: Object reference not set to an instance of an object.
   at PRoConEvents.AdKats.EmailHandler.<>c__DisplayClassd92.<SendReport>b__d8f() in c:\Users\B\Desktop\Procon\Golmud\Plugins\BF4\Temp\mruahtv3.0.cs:line 42272]

**Comment by ColColonCleaner** [comment]
Alright, checking.

**Comment by ColColonCleaner** [comment]
The first one here I just need to make look nicer, it had issues connecting to your email server.

The second is an actual bug i need to fix.

**Comment by ChaT0n** [comment]
I also noticed that servers crashes DIRECTLY after this error, (this issue was observed many times lately)

EXCEPTION-68039-42272-b__d8f-EmailSending10: [Error in email sending thread.][System.NullReferenceException: Object reference not set to an instance of an object.
at PRoConEvents.AdKats.EmailHandler.<>c__DisplayClassd92.b__d8f() in c:\Users\B\Desktop\Procon\Golmud\Plugins\BF4\Temp\mruahtv3.0.cs:line 42272]

**Comment by ColColonCleaner** [comment]
This has been fixed.

**Comment by jay7981** [comment]
i have triple checked my email settings and all are correct ..

[19:45:20 53] [AdKats] EXCEPTION-6810-D-EmailProcessingThreadLoop-EmailProcessing26: [Error occured in mail processing thread. skipping loop.][System.Security.SecurityException: Request for the permission of type 'System.Net.Mail.SmtpPermission, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.
   at System.Security.CodeAccessSecurityEngine.Check(Object demand, StackCrawlMark& stackMark, Boolean isPermSet)
   at System.Security.CodeAccessPermission.Demand()
   at System.Net.Mail.SmtpClient.Initialize()
   at System.Net.Mail.SmtpClient..ctor(String host, Int32 port)
   at PRoConEvents.AdKats.EmailHandler.EmailProcessingThreadLoop()
The action that failed was:
Demand
The type of the first permission that failed was:
System.Net.Mail.SmtpPermission
The Zone of the assembly that failed was:
MyComputer]
