### ISSUE TITLE
error in status monitor again

### ISSUE THREAD

**Issue by ChaT0n** [AdKats/AdKats#817]
[AdKats] EXCEPTION-68048-6345-<SetupStatusMonitor>b__af-StatusMonitor3: [Error in status monitor. Skipping current loop.][System.InvalidOperationException: Queue empty.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Queue`1.Peek()
   at PRoConEvents.AdKats.<SetupStatusMonitor>b__af() in c:\Users\B\Desktop\Procon\TDMNoshahr\Plugins\BF3\Temp\yefnxnhw.0.cs:line 6345]

**Comment by ColColonCleaner** [comment]
Fixed. Thanks.
