### ISSUE TITLE
Error just on procon layer restart

### ISSUE THREAD

**Issue by ChaT0n** [AdKats/AdKats#818]
[AdKats] EXCEPTION-68049-39645-GetDisplayPluginVariables-AccessFetching15: [Error while fetching display vars.][System.NullReferenceException: Object reference not set to an instance of an object.
   at PRoConEvents.AdKats.GetPingLimitStatus() in c:\Users\Breakmaster\Desktop\Procon\TDMZavodNight\Plugins\BF4\Temp\anvsae8l.0.cs:line 39645
   at PRoConEvents.AdKats.GetDisplayPluginVariables() in c:\Users\B\Desktop\Procon\TDMZavodNight\Plugins\BF4\Temp\anvsae8l.0.cs:line 1203]

**Comment by ColColonCleaner** [comment]
Huh. Checking.

**Comment by ColColonCleaner** [comment]
You're great by the way. Someone who actually has plugin debugging on and is posting issues regularly. Only a couple people are doing that and it really helps.

**Comment by ChaT0n** [comment]
You're welcome
By the way the above exception only shows up when the procn layer is rebooted, otherwise it doesn't. I've rebooted the server layer 3 times and 3 times it showed up

**Comment by ChaT0n** [comment]
Still having the error on one of the servers when the layer reboots (just on the reboot)

AdKats] EXCEPTION-68058-39658-GetDisplayPluginVariables-AccessFetching20: [Error while fetching display vars.][System.NullReferenceException: Object reference not set to an instance of an object.
   at PRoConEvents.AdKats.GetPingLimitStatus() in c:\Users\B\Desktop\Procon\TDMZavodNight\Plugins\BF4\Temp\1kz0x5vl.0.cs:line 39658
   at PRoConEvents.AdKats.GetDisplayPluginVariables() in c:\Users\Breakmaster\Desktop\Procon\TDMZavodNight\Plugins\BF4\Temp\1kz0x5vl.0.cs:line 1204]

**Comment by ColColonCleaner** [comment]
These are fixed.
