### ISSUE TITLE
 EXCEPTION-68049-12078 on hacker checker

### ISSUE THREAD

**Issue by ChaT0n** [AdKats/AdKats#821]
[13:10:10] [AdKats] ERROR-68049: [Error processing battlelog stats for AtKillller. Stats response did not contain vehicle stats data.]
[13:10:23] [AdKats] SQL updates fetched.
[13:10:27] [Battlelog Cache] Fetching stats for player 'AtKillller' with requestType 'Overview' failed!
[13:11:57] [AdKats] EXCEPTION-68049-12078-HackerCheckerThreadLoop-HackerChecker33: [Error while fetching new players to check.][System.InvalidOperationException: Collection was modified after the enumerator was instantiated.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Queue`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at PRoConEvents.AdKats.HackerCheckerThreadLoop() in c:\Users\B\Desktop\Procon\TDMNoshahr\Plugins\BF3\Temp\3t58plh4.0.cs:line 12078]
[13:12:57] [Battlelog Cache] No valid stats for player 'AtKillller' with requestType 'Overview'

**Comment by ColColonCleaner** [comment]
First error has to do with battlelog, if the player did not return vehicle data there is nothing the plugin can do. As you can see Battlelog Cache errored out for the same player.

For the hacker checker error, that shouldn't happen anymore.
