### ISSUE TITLE
EXCEPTION 68150-12430 HackerCheckerThreadLoop HackerChecker53

### ISSUE THREAD

**Issue by ChaT0n** [AdKats/AdKats#868]
EXCEPTION-68150-12430-HackerCheckerThreadLoop-HackerChecker53: [Error while fetching new players to check.][System.InvalidOperationException: Collection was modified after the enumerator was instantiated.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Queue`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at PRoConEvents.AdKats.HackerCheckerThreadLoop() in c:\Users\B\Desktop\Procon\TDMLocker\Plugins\BF4\Temp\7hoajxlz.0.cs:line 12430

**Comment by ColColonCleaner** [comment]
Fixed.
