### ISSUE TITLE
: [Command Previous Perm Ban not found in runAction]

### ISSUE THREAD

**Issue by sitekeeper** [AdKats/AdKats#870]
About 12 hours ago I started getting pages of these and it crashes Procon on 2 of 3 servers:

[10:57:43 61] [AdKats] SUCCESS: AdKats 6.8.1.53 startup complete [24s]. Commands are now online.
[10:57:47 54] [AdKats] EXCEPTION-68153-RunAction-ActionHandling30: [Command Previous Perm Ban not found in runAction]
[10:57:47 57] [AdKats] EXCEPTION-68153-RunAction-ActionHandling30: [Command Previous Temp Ban not found in runAction]
[10:57:47 57] [AdKats] EXCEPTION-68153-RunAction-ActionHandling30: [Command Previous Perm Ban not found in runAction]
[10:57:47 57] [AdKats] EXCEPTION-68153-RunAction-ActionHandling30: [Command Previous Temp Ban not found in runAction]
[10:57:47 57] [AdKats] EXCEPTION-68153-RunAction-ActionHandling30: [Command Previous Perm Ban not found in runAction]
[10:59:37 75] [AdKats] EXCEPTION-68153-RunAction-ActionHandling30: [Command Previous Perm Ban not found in runAction]
[10:59:37 75] [AdKats] EXCEPTION-68153-RunAction-ActionHandling30: [Command Previous Temp Ban not found in runAction]
[10:59:37 75] [AdKats] EXCEPTION-68153-RunAction-ActionHandling30: [Command Previous Perm Ban not found in runAction]
[10:59:37 75] [AdKats] EXCEPTION-68153-RunAction-ActionHandling30: [Command Previous Perm Ban not found in runAction]
[10:59:49 86] [AdKats] EXCEPTION-68153-RunAction-ActionHandling30: [Command Previous Perm Ban not found in runAction]
[10:59:49 86] [AdKats] EXCEPTION-68153-RunAction-ActionHandling30: [Command Previous Temp Ban not found in runAction]
[10:59:49 86] [AdKats] EXCEPTION-68153-RunAction-ActionHandling30: [Command Previous Perm Ban not found in runAction]
[10:59:49 86] [AdKats] EXCEPTION-68153-RunAction-ActionHandling30: [Command Previous Temp Ban not found in runAction]
[10:59:49 86] [AdKats] EXCEPTION-68153-RunAction-ActionHandling30: [Command Previous Perm Ban not found in runAction]
[10:59:49 86] [AdKats] EXCEPTION-68153-RunAction-ActionHandling30: [Command Previous Perm Ban not found in runAction]
[10:59:56 56] [Statslogger]Error: Error in UpdateCurrentPlayerTable: Maximum number of 3 transaction retrys exceeded (Transaction delete und Insert)
[10:59:56 56] [Statslogger]Error: Error in UpdateCurrentPlayerTable: 
[10:59:56 56] Message: Lock wait timeout exceeded; try restarting transaction
[10:59:56 56] Native: -2147467259
[10:59:56 56] Source: MySql.Data
[10:59:56 56] StackTrace:    at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at PRoConEvents.CChatGUIDStatsLogger.UpdateCurrentPlayerTable(List`1 lstPlayers)
[11:00:07 62] [AdKats] 11...
[11:00:08 64] [AdKats] 10...
[11:00:09 65] [AdKats] 9...
[11:00:10 67] [AdKats] 8...

Any Ideas?
Nothing has changed. DB @ NFO / Layer @ Branzone
Thanks
Bob

**Comment by ColColonCleaner** [comment]
https://forum.myrcon.com/showthread.php?6045-Advanced-In-Game-Admin-and-Ban-Enforcer-AdKats-6-8-0-0&p=131298&viewfull=1#post131298
