### ISSUE TITLE
version 6.9.0.262 returns start error (clean installation)

### ISSUE THREAD

**Issue by Graymanflo** [AdKats/AdKats#964]
Good afternoon, just grabbed latest build being v6.9.0.262 and I'd like to report that it gives this stacktrace on start (the plugin itself is not loading in):

`

[23:18:44 28] System.TypeLoadException: Could not load type 'PRoConEvents.Adkats' from assembly 'Adkats, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

Server stack trace: 
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at PRoCon.Core.Plugin.CPRoConPluginLoaderFactory.Create(String assemblyFile, String typeName, Object[] constructArguments)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at PRoCon.Core.Plugin.CPRoConPluginLoaderFactory.Create(String assemblyFile, String typeName, Object[] constructArguments)
   at PRoCon.Core.Plugin.PluginManager.LoadPlugin(String pluginClassName, CPRoConPluginLoaderFactory pluginFactory, Boolean blSandboxDisabled)
   at PRoCon.Core.Plugin.PluginManager.CompilePlugins(PermissionSet pluginSandboxPermissions, List`1 ignoredPluginClassNames)

`

Thanks.

**Comment by Graymanflo** [comment]
The filename was incorrect, my fault!
